import com.palantir.gradle.gitversion.VersionDetails
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    id("com.github.johnrengelman.shadow") version "6.0.0"
    id("com.google.cloud.tools.jib") version "2.4.0"
    id("com.palantir.git-version") version "0.12.3"

    // Apply the application plugin to add support for building a CLI application.
    application
}

val versionDetails: groovy.lang.Closure<VersionDetails> by extra

version = versionDetails().lastTag.replace("^v".toRegex(), "")

application {
    // Define the main class for the application.
    mainClassName = "io.github.wlezzar.jsql.MainKt"
}

jib {

    from {
        image = "openjdk:11-jre-slim"
    }

    to {
        image = "wlezzar/jsql"
        tags = setOf(project.version.toString(), "latest")
    }

    container {
        jvmFlags = listOf("-client")
        mainClass = application.mainClassName
    }
}


repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("org.apache.calcite:calcite-core:1.21.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.0")
    implementation("com.jakewharton.picnic:picnic:0.3.1")
    implementation("com.github.ajalt:clikt:2.8.0")
    implementation("com.github.ajalt:mordant:1.2.1")
    implementation("org.slf4j:slf4j-simple:1.7.26")
    implementation("com.github.ben-manes.caffeine:caffeine:2.8.0")
    implementation("com.google.protobuf:protobuf-java:3.12.2")


    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
}

tasks {
    withType<KotlinCompile> {
        kotlinOptions { jvmTarget = "11" }
    }
}
