name: Publish release packages

on:
  release:
    types: ["published"]

jobs:

  publish-jsql-packages:
    name: Publish packages without JDK

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '100'

      - name: set upload url
        id: fetch_release_data
        run: |
          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Package
        id: package
        run: |
          ./gradlew clean test distZip distTar

      - name: Upload zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: build/distributions/jsql.zip
          asset_name: jsql.zip
          asset_content_type: application/zip

      - name: Upload tar package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
          asset_path: build/distributions/jsql.tar
          asset_name: jsql.tar
          asset_content_type: application/zip

